# Generated by Django 4.2.7 on 2024-12-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customeravatar_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='video_button_url',
        ),
        migrations.AddField(
            model_name='hero',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='start_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='start_button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='video_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
