# Generated by Django 4.2.7 on 2024-12-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "About Section"},
        ),
    ]
