# Generated by Django 4.2.7 on 2024-12-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_about_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="feture_list",
            new_name="feature_list",
        ),
    ]
