# Generated by Django 4.2.7 on 2024-12-10 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_feture_list_about_feature_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="feature_list",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
