# Generated by Django 4.2.7 on 2024-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_about_feature_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="feature_list",
            field=models.TextField(blank=True, null=True),
        ),
    ]
