# Generated by Django 4.2.7 on 2024-12-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_about_feature_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="text_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
