# Generated by Django 4.2.7 on 2024-12-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_rename_title_line1_hero_title_line_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Features", help_text="Bo'limning nomi.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit",
                        help_text="Bo'limning umumiy izohi.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Tabning nomi (masalan, 'Modisit').", max_length=200
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Tab ichidagi katta sarlavha.", max_length=200
                    ),
                ),
                ("description", models.TextField(help_text="Tab uchun qisqacha matn.")),
                (
                    "points",
                    models.TextField(
                        help_text="Tab ichidagi ro'yxatdagi elementlar (yangi qatordan yozing)."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Tab uchun tasvir.", upload_to="features/"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tabning tartib raqami (kichik raqam birinchi bo'ladi).",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Qaysi bo'limga tegishli ekanligini belgilaydi.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="main.featuresection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Tab",
                "verbose_name_plural": "Feature Tabs",
                "ordering": ["order"],
            },
        ),
    ]
