# Generated by Django 4.2.7 on 2024-12-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_featuresection_featuretab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuretab",
            name="points",
            field=models.TextField(
                blank=True,
                help_text="Tab ichidagi ro'yxatdagi elementlar (yangi qatordan yozing).",
                null=True,
            ),
        ),
    ]
